version: "3.7"
services:
    dvwa:
        build: ./dvwa
        restart: unless-stopped
        volumes:
          - ./dvwa/logs/:/var/log/apache2/
        ports:
          - 8500:80
    nginx:
      build: ./nginx
      ports:
        - 8088:80
      volumes:
        - ./nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/conf/modsec/:/etc/nginx/modsec/
        - ./nginx/logs/:/var/log/nginx/